# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataExtraction
                                 A QGIS plugin
 This plugin provides raster data statistics.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by DimpleJain
        email                : jain23dimple@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'DimpleJain'
__date__ = '2023-11-29'
__copyright__ = '(C) 2023 by DimpleJain'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataExtraction class from file DataExtraction.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DataExtraction import DataExtractionPlugin
    return DataExtractionPlugin()
